extend = "build-tools/makefile.toml"

[env]
    CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
    __MAKE_README_CRATE_ROOT__           = "core"
    __MAKE_TEST_TASKS__                  = "test-default test-serde test-send_guard test-all-features"
    __MAKE_TOOLCHAINS__                  = "1.77 1.78 stable beta nightly"

[config]
    default_to_workspace = false

[tasks.test-default]
    args        = ["test", "--workspace"]
    category    = "Test"
    command     = "cargo"
    description = "Test with only the default features"
    toolchain   = "${__FIELDX_DEFAULT_TOOLCHAIN__}"

[tasks.test-serde]
    args        = ["test", "--workspace", "--features", "serde"]
    category    = "Test"
    command     = "cargo"
    description = "Test with 'serde' feature"
    toolchain   = "${__FIELDX_DEFAULT_TOOLCHAIN__}"

[tasks.test-send_guard]
    args        = ["test", "--workspace", "--features", "send_guard"]
    category    = "Test"
    command     = "cargo"
    description = "Test with 'serde' feature"
    toolchain   = "${__FIELDX_DEFAULT_TOOLCHAIN__}"

[tasks.test-all-features]
    args        = ["test", "--workspace", "--all-features"]
    category    = "Test"
    command     = "cargo"
    description = "Test with all features enabled"
    toolchain   = "${__FIELDX_DEFAULT_TOOLCHAIN__}"
