[package]
    authors.workspace      = true
    categories.workspace   = true
    description            = "Design patterns built on top of fieldx crate "
    edition.workspace      = true
    exclude.workspace      = true
    keywords.workspace     = true
    license-file.workspace = true
    name                   = "fieldx_plus"
    readme                 = "../README.md"
    repository.workspace   = true
    version                = "0.1.1-beta.1"

[dependencies]
    fieldx             = { workspace = true }
    fieldx_aux         = { workspace = true }
    fieldx_plus_macros = { workspace = true }

[dev-dependencies]
    fieldx    = { workspace = true }
    thiserror = { workspace = true }

[features]
    send_guard = ["fieldx/send_guard"]
    serde      = ["fieldx/serde"]
