[package]
    edition = "2021"
    name    = "fieldx_plus_macros"
    version = "0.1.0"

[dependencies]
    darling     = { workspace = true }
    fieldx      = { workspace = true }
    fieldx_aux  = { workspace = true }
    proc-macro2 = { workspace = true }
    quote       = { workspace = true }
    syn         = { workspace = true }

[lib]
    proc-macro = true

[features]
    serde = []
