name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  with_features:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        toolchain:
          - 1.78
          - stable
          - nightly
        feature:
            - ""
            - "async-tokio"
            - "async-lock"
            - "sync"
            - "serde"
            - "async-tokio,sync"
            - "async-lock,sync"
            - "async-tokio,serde"
            - "async-lock,serde"
            - "async-tokio,sync,serde"
            - "async-lock,sync,serde"
        exclude:
          - os: windows
            toolchain: nightly
    steps:
      - uses: actions/checkout@v4
      - run: cargo +${{ matrix.toolchain }} test --verbose --all --features ${{ matrix.feature }}
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup default nightly
      - run: cargo install cargo-docs-rs
      - run: cargo docs-rs -p fieldx

